USE [CHUNGKHOAN]
GO

/****** Object:  Trigger [dbo].[TR_After_LENHKHOP]    Script Date: 5/22/2021 12:40:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER TRIGGER  [dbo].[TR_After_LENHKHOP] 
   ON  [dbo].[LENHKHOP] 
   AFTER INSERT, UPDATE, DELETE 
AS 
BEGIN
	DECLARE 
		@CrsrVar CURSOR,
		@MACP char(7),
		@GIAKHOP FLOAT, 
		@KLKHOP INT
	SET @CrsrVar = CURSOR KEYSET FOR (SELECT DISTINCT MACP FROM LENHDAT)
	OPEN @CrsrVar 
	FETCH NEXT FROM @CrsrVar INTO @MACP
	WHILE(@@FETCH_STATUS <>-1)
	BEGIN
		SET	@GIAKHOP = 0
		SET	@KLKHOP = 0
		SELECT top 1 @GIAKHOP = LENHKHOP.GIAKHOP , @KLKHOP= LENHKHOP.SOLUONGKHOP 
		FROM LENHKHOP, LENHDAT
		WHERE LENHKHOP.IDLENHDAT = LENHDAT.ID AND LENHDAT.MACP = @MACP  AND CAST(LENHKHOP.NGAYKHOP AS DATE) = CAST(GETDATE() AS DATE )
		ORDER BY LENHKHOP.NGAYKHOP DESC;

		UPDATE BANGGIATRUCTUYEN
	 	SET GIAKHOPLENH = @GIAKHOP,
			KLKHOPLENH = @KLKHOP
		WHERE MACP = @MACP
		FETCH NEXT FROM @CrsrVar INTO @MACP
	END
END
CLOSE @CrsrVar 
DEALLOCATE @CrsrVar

GO


